### ISSUE TITLE
User experience when the player is kicked out of a game

### ISSUE THREAD

**Issue by quantuumsnot** [arcadia-redux/12v12#146]
Everyone with a common sense will expect when a player is kicked out of a game to be only kicked, not banned for joining in a new arcade game the next 60 mins. Why? Because:

1. The reason being kicked is not always based on feeding detection (which is extremely funny because some feeders late game become the best supports) or other shitty behavior. For example saying the ugly truth early game to your team or trying to give them some advices always lead to another lose, kick and uninstalling dota for the N-th time
2. Kicking a player in 12v12 battle means ~9% balance diff in team's powers which is the exact opposite of the main goal of ALL mod's updates (excluding bug fixes)

**Comment by vkirilyuk** [comment]
Devs are too braindead to implement it in a decent way.

**Comment by quantuumsnot** [comment]
> Devs are too braindead to implement it in a decent way.

I don't mind if they receive donations and `supporter` fees but the culprit is still here - balance issues

**Comment by throwaway-317** [comment]
@quantuumsnot Nobody cares if they received donation the way dota does - cosmetics and non-mechanical perks. Right now, however, I always hold my breath during hero selection praying that we got no donators in the game.

To devs: I see you addressed the issue and provided a clear timeline for solution, good job. https://steamcommunity.com/sharedfiles/filedetails/comments/1576297063 Also, seems like the only way to attract your attention is to start swearing, looks legit too.

**Comment by quantuumsnot** [comment]
> @quantuumsnot Nobody cares if they received donation the way dota does - cosmetics and non-mechanical perks. Right now, however, I always hold my breath during hero selection praying that we got no donators in the game.

They are easily spotted -  if you see during high/normal supporter hero selection countdown someone picks Mirana/Zeus/Silencer/Invoker/Chen/Treant/Crystal/Techies/Tinker then you know the drill xD

**Comment by throwaway-317** [comment]
> Chen/Crystal
Damn you have classy supporters. Mine are PA / Sniper / Riki / Drow / Slark. Sometimes I get a pudge with +450 cast range, that's nice too.
The reason I was so pissed was because I try to pick the shittiest heroes for the mode and prove they work. One time it was TA and, admittedly, got 0-5-1 before getting kicked. First kick after 200+ games with ~65% winrate. I would've accepted 'feeder debuff', but instead received abandon for being a troll?

Besides, there is one troll in, dunno, 50 games. There is no skill-based matchmaking, we are usually lucky to gather full squad at all. Naturally some people would be Guardians and some would be Divines. Expecting everyone to have spectacular performance is setting yourself up for a failure. So the 'kick troll' feature is dominantly used to say 'how dare you to not meet my expectations is this ultra casual mode?. 

Usually when the feature is broken it's disabled until solution is created, not left to piss off people for no particular reason.

**Comment by darklordabc** [comment]
Well if we just go straight ahead and remove the kick troll feature, it would mean that we piss a lot of people off too because trolls could do what they do. Do you have a suggestion on how to improve the kick troll feature? Maybe have it require more votes?

**Comment by vkirilyuk** [comment]
How about applying feeder debuff too? They would die at least once, make the respawn 3 minutes or something.

**Comment by darklordabc** [comment]
We could make the first time you get voted to kick, you cannot play for 5 minutes, but second time, you get ejected from game?

**Comment by darklordabc** [comment]
But that might not fix your complaint, because they may just kick you again.

**Comment by vkirilyuk** [comment]
That would be legit good solution. In the case with TA game I didn't even had a chance to apologize / redeem myself. I wanted to farm for next 5 minutes until I get some items and ready to fight again. At that moment I saw notification that I'm voted for kicking and was out before I could've reacted.

**Comment by vkirilyuk** [comment]
Also Hanlon's Razor:  "Never attribute to malice that which is adequately explained by stupidity"

**Comment by vkirilyuk** [comment]
Do you have examples of legit trolling? So far in the comments I've seen only Venomancer blocking neutral camps with wards. Tiny / Furion could be disabled by 'Disallow help' feature. Intentional feeding is covered by feeder debuff.

**Comment by darklordabc** [comment]
Trolling could also just be being racist or abusive.

**Comment by vkirilyuk** [comment]
Chat mute fixes that. A stretch might be to implement some persistent memory so you get to mute player only once and it stays muted in the following games.

**Comment by vkirilyuk** [comment]
'To catch a troll, you have to think as a troll'. Now I'm trying to come up with a creative way to annoy my team. Naga ult in the midst of a fight is a good candidate. :-)

Another possible fix: when kicking a player, ask for a reason from the initiator. And 'dying a lot' should not be one of them. This way people who vote can evaluate whether it's justifiable instead of expressing their anger that the game was lost during the picking stage.

**Comment by darklordabc** [comment]
We already ask for a reason. It shows what reason the initiator has chosen.

**Comment by throwaway-317** [comment]
> ["feeding"] = true,

I'd just remove this one and leave it to feeder debuff.

**Comment by quantuumsnot** [comment]
> Well if we just go straight ahead and remove the kick troll feature, it would mean that we piss a lot of people off too because trolls could do what they do. Do you have a suggestion on how to improve the kick troll feature? Maybe have it require more votes?

Usually in huge percentage of the games there's no time for kicking some1 when there are fights everywhere on the map

**Comment by quantuumsnot** [comment]
The other part of the problem is in the attitude of PRO player mentioned earlier by 

> So the 'kick troll' feature is dominantly used to say 'how dare you to not meet my expectations is this ultra casual mode?.

Kick feature is nothing more that digital version of the modern judiciary - we decide AFTER after the crime has been committed

**Comment by quantuumsnot** [comment]
Another problem is the end-game kick especially when exploiting the game balance (mainly russians ... sorry, no sorry but that's the facts). They usually kick after they won the game, the initiation is always a russian from your team votekicking another one of your team

**Comment by quantuumsnot** [comment]
Statistics from 100 games:
Kick feature is abused in each game - over 88% at end-game

Conclusion: 
It's not worth it playing 12v12 anymore while mod gives kick feature to ***put some random insult word here***
