### ISSUE TITLE
Allow only solo players to gain mmr

### ISSUE THREAD

**Issue by SanctusAnimus** [arcadia-redux/12v12#230]
Requires:
 - Setting a flag on a player to indicate if he's in party or not (already kind of present in form of Party Highlighter)
 - Sending it to server to decide on mmr gain

**Comment by Draze22** [comment]
In my opinion it would be far better to add party mmr and a party mmr leaderboard. Conversation on this here: https://discordapp.com/channels/694473865983819847/694478568234680400/844821046074671134

**Comment by SanctusAnimus** [comment]
I don't think it's worth it since it's so easily abusable

**Comment by Draze22** [comment]
> I don't think it's worth it since it's so easily abusable

In what way/s is it abusable?

**Comment by SanctusAnimus** [comment]
Well, unlike the usual dota, where getting in the same match without party has a low chance of happening, in custom games you can just jump in friend lobbies, meaning that whole party distinguishing is meaningless

**Comment by SanctusAnimus** [comment]
And in any way, this issue is a darklords decision, go argue with him on that subject

**Comment by Draze22** [comment]
> Well, unlike the usual dota, where getting in the same match without party has a low chance of happening, in custom games you can just jump in friend lobbies, meaning that whole party distinguishing is meaningless

1. You can't garuantee you'll be on the same team as your friends unless you're in a party.
2. The main goal would to be to change the perceptions of players rather than make the game more fair. Creating a party mmr system/leaderboard would allow solo players to compare their mmr only to other solo leaderboard players (which would be lower than party leaderbaord players) and therefor feel better about their mmr.
