### ISSUE TITLE
make shadow realm unaffected by buff duration amplification

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#359]
Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/882192652504821860)

**Comment by Draze22** [comment]
How about we nerf one of the >55% winrate heroes:
![image](https://user-images.githubusercontent.com/63279022/131492462-3105adf6-5aa9-4ae2-b017-5ec244bcbb93.png)

Instead of a 48% winrate hero:
![image](https://user-images.githubusercontent.com/63279022/131492516-272f262c-a367-4796-9ad6-88018756299a.png)

**Comment by Sheodar** [comment]
Turned off for both mods. Other heroes problems - that's other issues.

**Comment by Sheodar** [comment]
Turned off for both mods*
