### ISSUE TITLE
alchemist aghanims buff doesnt show on end screen

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#423]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/898059075504459787)

**Comment by Sheodar** [comment]
@AustraliaIsMyCity If we want add more info in endgame table we should change design of this. Like horizontal sctoll at least. Because we already have full screen info for all screen resolution.
If we will change it we can add any addition info. Like legion commander duel damage / used tome of knowledge, update visual part. Main think from me - just try to copy dota's endgame stats. 
Only one problem - game can close it and trigger finish automatic (several minutes after player see endgame table).

**Comment by AustraliaIsMyCity** [comment]
Just change the aghs buff to check for regular aghs blessing as well as alchemist aghs blessing?

**Comment by Sheodar** [comment]
Oh lul, i thought need add more icons :D Just forgot we already have agh/shard tracking. Will add it.

**Comment by Sheodar** [comment]
Added
