### ISSUE TITLE
Two players with the same IP address can't play 12v12 at the same time

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#517]
![image](https://user-images.githubusercontent.com/63279022/157160271-20fedfa8-85b7-4ae5-8db6-d91a0b20fdc5.png)

**Comment by GeneralDotV2** [comment]
That would be a routing issue or NAT issue on their home network.

**Comment by GeneralDotV2** [comment]
I tested this with both 2 Steam accounts, 1 on each team. Also tested with 3 accounts with 2 on one team and 1 one the opposite team. All were able to connect and play on the same LAN with the same ip address with no disconnect or connection issues whatsoever. I presume this is an issue with the way this player has their router / NAT setting setup and/or access point / wifi configuration. Most likely a NAT conflict based on my knowledge of how network equipment functions.

**Comment by GeneralDotV2** [comment]
Apparently this is an issue still since Feb 25th this year.
https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/V/ShareX/2022/27/03/Discord_0MIpjVTsg7.png
https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/V/ShareX/2022/27/03/steamwebhelper_mTlelxPISu.png

I'll try to one again reproduce what this 12v12 player is saying on my end.
