### ISSUE TITLE
Rework supporter couriers/item delivery

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#614]
The current implementation, while very convenient in most cases has some major downsides and some bugs/exploits:

- There's a significant delay before you can use your courier to deliver items, pick up dropped gems, etc.
- If you buy the wrong item/change your mind you can't sell it because it gets instantly delivered (this matters most when items combine unexpectedly and you accidentally buy extra copies of an item because of it).
- It's really OP when it allows you to almost instantly switch neutral items in the middle of a fight (free dispel, Spider Legs to get off a cliff, Ex Machina to refresh BKB, etc).
- It also has a bug where if you have consumables in your stash you can just buy a regular item and the consumables get instantly delivered with the regular item.

In my opinion we should make supporter couriers invulnerable, twice as fast as regular couriers, and remove the existing courier modifications and instant item delivery.

**Comment by SanctusAnimus** [comment]
this WILL cause massive backlash for sure

**Comment by Crigeket** [comment]
I'm in for it ! 

Just let the sideshop component to it

### **_"If you buy the wrong item/change your mind you can't sell it because it gets instantly delivered (this matters most when items combine unexpectedly and you accidentally buy extra copies of an item because of it)."_** 

This was a good thing, this could happen without the courier so this is the player fault, they need to keep watch of what they buy.

### 
**_"It's really OP when it allows you to almost instantly switch neutral items in the middle of a fight (free dispel, Spider Legs to get off a cliff, Ex Machina to refresh BKB, etc)."_** 

Do people really do this ? Probably on asian server , or 1 guy every 20 game.
### 

but in global that mean : you get your item with a delay but consumable will be there faster (abuse of smoke / healing much more viable), invulnerable mean free gem pickup (even with the speed) AND FINALY .........FREE VISION !!!!!

**Comment by Draze22** [comment]
> but in global that mean : you get your item with a delay but consumable will be there faster (abuse of smoke / healing much more viable), invulnerable mean free gem pickup (even with the speed) AND FINALY .........FREE VISION !!!!!

We could increase the courier slow from carrying consumables, prevent the courier from providing vision unless it's not moving (to allow using courier to give vision of cliff spots) and make the courier vulnerable and slow when it's carrying Gem of Truesight.

**Comment by SanctusAnimus** [comment]
I strongly disagree on touching this feature. 12v12 is an established game already, and touching it's monetization scheme now makes very little sense. 
Boosters are main income source (as currency packs are borderline useless in 12v12), and chinese players already complain about price being quite high - nerfing current offer will damage that income for no apparent profit otherwise then being more "balanced", even though it will still remain pay to win feature

**Comment by Draze22** [comment]
I'll go back to the drawing board to try and fix the issues with the current system without straight up nerfing supporter benefits.
